correct module path (#261)
module path for `cfn_yaml` does not include `decode` :

```
In [5]: import cfnlint.core

In [6]: filename = 'test.yaml'

In [7]: template = cfnlint.decode.cfn_yaml.load(filename)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-8c164c8b9ade> in <module>()
----> 1 cfnlint.decode.cfn_yaml.load(filename)

AttributeError: module 'cfnlint' has no attribute 'decode'

In [8]: template = cfnlint.cfn_yaml.load(filename)
In [9]:
```